### ISSUE TITLE
[JIRA] Trying to link sentry issue to Jira issue

### ISSUE THREAD

**Issue by ghost** [getsentry/sentry-plugins#227] opened 2017-09-06 14:12 UTC
### Steps to reproduce:

1. Open Sentry issue
2. Select `Link to existing Jira issue`
3. Try to search Jira issue by ID like `AB1234-123`

### Expected result:

Issue will be displayed in link

### Actual result:

Message with `no results were found`.

But if you try to search by Jira issue name - you will get expected issue in result list.

#### Versions:

* JIRA v7.4.2
* Sentry 8.19.0

**Comment by nicktong** [comment] 2017-10-03 09:31
Hi, is there any update on this bug?

**Comment by apastuhow** [comment] 2017-10-03 11:58
It seems no

**Comment by jcasner** [comment] 2018-03-21 17:48
Duplicate of #111?

**Comment by lzzparis** [comment] 2018-12-03 20:14
We're having the same problem which makes the integration only partially useful.  We have no problem creating a new Jira ticket from Sentry, but it's almost impossible to link existing Jira issues (other than the ones suggested before you type anything, perhaps the 5 most recently created?)

**Closed** 2019-11-20 22:30 UTC
