### ISSUE TITLE
Unable to create GitLab integration

### ISSUE THREAD

**Issue by shresthsumanifesca** [getsentry/sentry-plugins#479] opened 2019-05-16 13:34 UTC
## Important Details - 
  On-Premise docker

Description
When I try to link my project, everything works until the last step where I get:
![1](https://user-images.githubusercontent.com/50139944/57857693-f272a700-77ef-11e9-86fc-f3588315bfaf.PNG)
![2](https://user-images.githubusercontent.com/50139944/57857694-f272a700-77ef-11e9-8c8f-c590baed67b4.PNG)

Not sure where I went wrong!

**Comment by markstory** [comment] 2019-05-16 14:45
Duplicate of getsentry/sentry#13245

**Closed by markstory** 2019-05-16 14:45 UTC
